development:
  adapter: mysql
  database: queriac_development
  username: root
  # password: ereiamJH
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: queriac_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: monoquery_production
  username: mq_production
  password: ereiamJH
  
# production:
#   adapter: mysql
#   database: db1939_queriac
#   username: db1939
#   password: 123456
#   socket: /tmp/mysql.sock

