development:
  adapter: mysql
  database: queriac_development
  username: root
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: queriac_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: monoquery_production
  username: mq_production
  password: <%= ENV['QUERIAC_DB_PASSWORD'] %>