# == Schema Information
# Schema version: 12
#
# Table name: users
#
#  id                        :integer(11)     not null, primary key
#  login                     :string(255)     
#  email                     :string(255)     
#  crypted_password          :string(40)      
#  salt                      :string(40)      
#  created_at                :datetime        
#  updated_at                :datetime        
#  remember_token            :string(255)     
#  remember_token_expires_at :datetime        
#  activation_code           :string(40)      
#  activated_at              :datetime        
#  default_command_id        :integer(11)     
#  first_name                :string(255)     
#  last_name                 :string(255)     
#  per_page                  :integer(11)     
#

require 'digest/sha1'
class User < ActiveRecord::Base
  has_many :commands
  has_many :queries
  has_many :tags, :through => :commands
  
  belongs_to :default_command, :class_name => "Command", :foreign_key => :default_command_id
  
  # Virtual attribute for the unencrypted password
  attr_accessor :password

  validates_presence_of     :login, :email
  validates_presence_of     :password,                   :if => :password_required?
  validates_presence_of     :password_confirmation,      :if => :password_required?
  validates_length_of       :password, :within => 4..40, :if => :password_required?
  validates_confirmation_of :password,                   :if => :password_required?
  validates_format_of       :login,   :with => /[a-zA-Z0-9_]{3,16}/
  validates_length_of       :email,    :within => 3..100
  validates_uniqueness_of   :login, :email, :case_sensitive => false
  before_save :encrypt_password
  before_create :make_activation_code 
  
  # def tags
  #   self.commands.find(:all, :select => :id, :include => :tags).map(&:tags).flatten.uniq.sort_by(&:name)
  # end
  
  # def tags_with_counts
  #   tags = {}
  #   self.commands.find(:all, :select => :id, :include => :tags).map(&:tags).flatten.sort_by(&:name).each do |tag|
  #     tags[tag.name] = tags.has_key?(tag.name) ? tags[tag.name]+1 : 1
  #   end
  #   tags.sort
  # end
  
  # def after_create
  #   g = self.commands.create!(
  #     :name => "Google Quicksearch", 
  #     :keyword => "g",
  #     :url => "http://www.google.com/search?q=(q)",
  #     :description => "Performs a basic Google search."
  #   )
  #   g.tags = "google"
  #   g.save
  #   
  #   mq = self.commands.create!(
  #     :name => "My Queriac Commands", 
  #     :keyword => "mq",
  #     :url => "http://queri.ac/#{self.login}/",
  #     :description => "A shortcut to a list of my queriac commands."
  #   )
  #   mq.tags = "queriac"
  #   mq.save
  # 
  #   gms = self.commands.create!(
  #     :name => "Gmail Search", 
  #     :keyword => "gms",
  #     :url => "http://queri.ac/#{self.login}/",
  #     :description => "Search your gmail. If you're not logged in you'll be directed to the Gmail login page. Examples..\ngms dog\ngms is:starred mom\ngms label:todo"
  #   )
  #   gms.tags = "google gmail mail email"
  #   gms.save
  # 
  # end
  
  def home_path
    "/#{login}/"
  end
  
  def tag_path(tag)
    "/#{login}/commands/tag/#{tag}"
  end
  
  def commands_path
    "/#{login}/commands/"
  end
  
  def default_command_path(query)
    "/#{login}/default_to #{default_command.keyword} #{query}"
  end
  
  def default_command?
    !default_command_id.nil?
  end
  
  # Remaining public methods generated by restul_authentication
  #------------------------------------------------------------------------------------------------------------------
  
  # Activates the user in the database.
  def activate
    @activated = true
    self.attributes = {:activated_at => Time.now.utc, :activation_code => nil}
    save(false)
  end

  def activated?
    activation_code.nil?
  end

  # Returns true if the user has just been activated.
  def recently_activated?
    @activated
  end
  
  # Authenticates a user by their login name and unencrypted password.  Returns the user or nil.
  def self.authenticate(login, password)
    u = find :first, :conditions => ['login = ? OR email = ?', login, login] # need to get the salt
    u && u.authenticated?(password) ? u : nil
  end

  # Encrypts some data with the salt.
  def self.encrypt(password, salt)
    Digest::SHA1.hexdigest("--#{salt}--#{password}--")
  end

  # Encrypts the password with the user salt
  def encrypt(password)
    self.class.encrypt(password, salt)
  end

  def authenticated?(password)
    crypted_password == encrypt(password)
  end

  def remember_token?
    remember_token_expires_at && Time.now.utc < remember_token_expires_at 
  end

  # These create and unset the fields required for remembering users between browser closes
  def remember_me
    remember_me_for 1.year
  end

  def remember_me_for(time)
    remember_me_until time.from_now.utc
  end

  def remember_me_until(time)
    self.remember_token_expires_at = time
    self.remember_token            = encrypt("#{email}--#{remember_token_expires_at}")
    save(false)
  end

  def forget_me
    self.remember_token_expires_at = nil
    self.remember_token            = nil
    save(false)
  end

  protected
    # before filter 
    def encrypt_password
      return if password.blank?
      self.salt = Digest::SHA1.hexdigest("--#{Time.now.to_s}--#{login}--") if new_record?
      self.crypted_password = encrypt(password)
    end
    
    def password_required?
      crypted_password.blank? || !password.blank?
    end

    
    def make_activation_code
      self.activation_code = Digest::SHA1.hexdigest( Time.now.to_s.split(//).sort_by {rand}.join )
    end 
end
